name: CD Todo API

"on":
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: self-hosted

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-api:${{ github.sha }} .

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-api:${{ github.sha }}

      - name: Import image into k3d
        run: |
          k3d image import ${{ secrets.DOCKER_USERNAME }}/todo-api:${{ github.sha }} -c todo-cluster

      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/todo-api `
            todo-api=${{ secrets.DOCKER_USERNAME }}/todo-api:${{ github.sha }} `
            -n todo

          kubectl rollout status deployment/todo-api -n todo